### PR TITLE
Add RSAGA 1.0.0 post

### PR DESCRIPTION
**Pull request by be-marc**
I wrote a blog post for the release of RSAGA 1.0.0 and the integration into the r-spatial community. Not quite sure if everything went right so feel free to change something.

### CODE REVIEW

**Comment by edzer** [comment]
Nice! Could you please add one paragraph at the start explaining what SAGA is, what it does, and where it is found? Maybe also that it runs on windows, linux and Mac (if that is the case)?

**Comment by be-marc** [comment]
Sorry for the delay. I updated the blog post.

**Comment by edzer** [comment]
And you're sure you don't want any graphics in it, right?

**Comment by be-marc** [comment]
Graphics are always nice but I think it is okay like that. Maybe I can write a blog post in the future about the workflow with RSAGA. This would be better place for some graphics of the calculated raster or shapefiles.

**Comment by edzer** [comment]
OK thanks, I've tweeted it!

**Pull request merged**
