### PR TITLE
Tutorial on reading and writing data in sf

### PR DESCRIPTION
**Pull request by kadyb**
Let me know if you have any comments and suggestions.

### CODE REVIEW

**Comment by kadyb** [comment]
Hi @edzer, could you look into this if you find time?

**Comment by edzer** [comment]
things are a bit hectic a.t.m., will get back soon I hope!

**Comment by kadyb** [comment]
Hello, any news?

**Comment by edzer** [comment]
I have troubles rendering it locally, will try to fix it soon

**Comment by kadyb** [comment]
Hi @edzer, do you have time to finalize it? If you are busy or have other plans, please let me know. I asked Jakub and Robin and it would be possible to publish it on their blog if needed.

**Comment by edzer** [comment]
I really should migrate this blog to quarto, I no longer have good tools to check things locally before committing / merging. Let's see how this comes out!

**Comment by kadyb** [comment]
Thanks! The only problem I see is missing images. And for some reason, the first-level headers are smaller than the second-level headers (e.g. "Vector loading" and "Shapefile (.shp)"), but this is not super important.

**Comment by kadyb** [comment]
One more thing :smiley: Didn't you render this script twice? There is warning that the file `data/capitals.shz` already exists:

```r
write_sf(capitals, "data/capitals.shz", driver = "ESRI Shapefile")

## Warning in CPL_write_ogr(obj, dsn, layer, driver,
## as.character(dataset_options), : GDAL Error 6: .shz does not support layer
## deletion
```

**Comment by edzer** [comment]
the warning is now gone. Now the images...

**Comment by edzer** [comment]
OK like this, or do you want me to update the date?

**Comment by kadyb** [comment]
Great! Ok, you can update the date.

**Pull request merged**
