### PR TITLE
post on quantities - first prototype

### PR DESCRIPTION
**Pull request by Enchufa2**
Here we go. Comments welcome.

BTW, what's the workflow to convert the Rmd into an md for Jekyll?

### CODE REVIEW

**Comment by edzer** [comment]
Trying to install quantities from `master`, but seeing (with units from master):
```
* installing to library ‘/home/edzer/R/x86_64-pc-linux-gnu-library/3.4’
* installing *source* package ‘quantities’ ...
** R
** byte-compile and prepare package for lazy loading
Warning: replacing previous import ‘errors::%*%’ by ‘units::%*%’ when loading ‘quantities’
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Warning: replacing previous import ‘errors::%*%’ by ‘units::%*%’ when loading ‘quantities’
Error: package or namespace load failed for ‘quantities’:
 object 'drop_errors' not found whilst loading namespace 'quantities'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/edzer/R/x86_64-pc-linux-gnu-library/3.4/quantities’
* restoring previous ‘/home/edzer/R/x86_64-pc-linux-gnu-library/3.4/quantities’
```
The workflow (obviously!) is [here](https://github.com/r-spatial/r-spatial.org/blob/gh-pages/_rmd/makefile). Change the first line.

**Comment by Enchufa2** [comment]
Ah, ok, I didn't see the makefile.

Regarding the installation of quantities, it requires both the master version of units *and* errors.

**Comment by Enchufa2** [comment]
Converted. Preview (more or less) [here](https://enchufa2.github.io/r-spatial.org/r/2018/03/01/quantities-first-prototype.html).

**Comment by edzer** [comment]
It runs now, thanks. I'm full with meetings Today; should be able to comment by Tomorrow.

**Comment by Enchufa2** [comment]
Great, thanks!

**Comment by edzer** [comment]
(merged manually)

**Comment by Enchufa2** [comment]
Thanks! What happened to the plot?

**Comment by edzer** [comment]
Thanks - it's there now.

**Pull request closed without merging**
