### PR TITLE
Create  	2018-05-22-geocompr-erum.markdown

### PR DESCRIPTION
**Pull request by Robinlovelace**
Heads-up @Nowosad and @Jannes-m - any last minute changes? Also @edzer any comments / suggestions very welcome before this goes live.

### CODE REVIEW

**Comment by edzer** [comment]
Nice blog post! Since you do references, please add some relevant references, at least to

-   Roger S. Bivand, Edzer Pebesma, Virgilio Gomez-Rubio, 2013. Applied   spatial data analysis with R, Second edition. Springer, NY.   http://www.asdar-book.org/
-   Pebesma, E., 2018. Simple Features for R: Standardized Support for Spatial Vector Data. The R Journal,   https://journal.r-project.org/archive/2018/RJ-2018-009/
-   Robert J. Hijmans (2017). raster: Geographic Data Analysis and Modeling. R package version 2.6-7.   https://CRAN.R-project.org/package=raster

and check for typos.

**Comment by Robinlovelace** [comment]
Will do, cheers for the minireview.

**Comment by Robinlovelace** [comment]
Just updated it accordingly. Pls review, change the filename as appropriate, to `2018-05-29-geocompr-erum.markdown` I imagine, and it should be good to go!

**Comment by Robinlovelace** [comment]
Nudge @edzer let us know if you spot any other improvements we could make before this goes live!

**Comment by Robinlovelace** [comment]
This is now live! Heads-up @jannes-m https://www.r-spatial.org/r/2018/05/31/geocompr-erum.html

**Pull request merged**
