### PR TITLE
post on quantities - parsing data

### PR DESCRIPTION
**Pull request by Enchufa2**
Second milestone. Preview (kind of) [here](https://enchufa2.github.io/r-spatial.org/r/2018/05/07/parsing-quantities.html). As always, comments welcome!

### CODE REVIEW

**Comment by edzer** [comment]
Great piece! Happy to publish as is. Is it an idea to add a "Next steps" section, with an outlook of what is to come in this project? I'll publish on Monday, a better day for tweets.

**Comment by Enchufa2** [comment]
Next steps added + date changed + some fixes.

**Comment by Enchufa2** [comment]
It seems that the post was not deployed, probably due to [this](https://andyc.tech/2016/04/08/Future-Posts.html)

**Comment by edzer** [comment]
I gave it a kick, now it's there.

**Comment by Enchufa2** [comment]
Great, thanks!

**Pull request merged**
