### PR TITLE
geostan introduction

### PR DESCRIPTION
**Pull request by ConnorDonegan**
A tutorial for spatial regression using the geostan package

### CODE REVIEW

**Comment by ConnorDonegan** [comment]
I wasn't able to build the site locally (at least not correctly) but did my best to copy the style of previous pull requests. 

The content is basically the same as shared via e-mail with @edzer.

**Comment by edzer** [comment]
Please check online, but LGTM! Thanks a lot,

**Comment by ConnorDonegan** [comment]
Yeah it came out right, thanks so much!

**Comment by edzer** [comment]
Advertised here: https://mastodon.social/@edzer/112898552133066068 - please share!

**Pull request merged**
