### PR TITLE
mapedit 0.2.0 post

### PR DESCRIPTION
**Pull request by timelyportfolio**
@tim-salabim, I believe this is ready.  I added install instructions for `mapview`, `leaflet.extras`, and `mapedit`.  Please confirm.  Thanks.

### CODE REVIEW

**Comment by tim-salabim** [comment]
confirmed!

**Comment by timelyportfolio** [comment]
@edzer, please let us know what we need to do to get this merged.  Thanks!

**Comment by edzer** [comment]
`images/mapedit_020_selectModules_shiny.gif` is still missing.

**Comment by timelyportfolio** [comment]
@edzer so sorry about that.  Should be fixed now.

**Comment by edzer** [comment]
Now online; pls verify. Thanks for the great work!

**Comment by timelyportfolio** [comment]
Thanks!!!

**Pull request merged**
