### PR TITLE
intro to mapedit blog post

### PR DESCRIPTION
**Pull request by timelyportfolio**
This contains an Intro to mapedit blog post that I tried to copy into the template I saw for other posts.  The pull currently contains the `Rmd` and images.  I could not find where to make the adjustments to build the post.  I would appreciate guidance.

cc @tim-salabim

### CODE REVIEW

**Comment by edzer** [comment]
I had to modify a few small things, but it's working now. You need jekyll to run it locally. Let me know when I should publish it (merge = publish).

**Comment by tim-salabim** [comment]
I will mention the post in tomorrow's webinar, so anytime before then is fine. Though I see I can also merge...

**Comment by edzer** [comment]
The blog is up.

**Comment by tim-salabim** [comment]
Cool! Thanks!

**Comment by timelyportfolio** [comment]
💯 Thanks!!!!

**Pull request merged**
