### PR TITLE
announcing mapedit 0.5.0

### PR DESCRIPTION
**Pull request by timelyportfolio**
This post announces `mapedit` version [`0.5.0`](https://github.com/r-spatial/mapedit/releases/tag/v0.5.0) which adds a new editor `leafpm` using the [Leaflet.pm](https://github.com/codeofsumit/leaflet.pm) plugin.

@edzer or anyone else, do we need to do more than add `Rmd` post and images.  Thanks!!

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@tim-salabim do you remember if there is anything else we need to do here?  I looked back, and I realized this pull was missing `markdown` so I added that.

**Comment by tim-salabim** [comment]
@timelyportfolio I am not sure really, @edzer manages the blog posts and I am still a bit confused by the whole process. I could just press the green button, but don't wanna mess things up... :-)

**Comment by edzer** [comment]
Pushing that button would not have worked well - I agree it's (too) convoluted. But published now - thanks! Leaving the tweeting to you...

**Comment by tim-salabim** [comment]
Thanks @edzer & @timelyportfolio !!

**Comment by tim-salabim** [comment]
On a second look, I don't see the animated gifs...

**Comment by edzer** [comment]
Thanks, they should be there now.

**Comment by tim-salabim** [comment]
Perfect! Thanks!

**Pull request merged**
